// <auto-generated />
using LogVault.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LogVault.Infrastructure.Migrations
{
    [DbContext(typeof(LogVaultDbContext))]
    [Migration("20260310010251_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.3");

            modelBuilder.Entity("LogVault.Domain.Entities.AlertFired", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AlertRuleId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EmailSent")
                        .HasColumnType("INTEGER");

                    b.Property<long>("FiredAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TriggeringEventId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AlertRuleId");

                    b.HasIndex("FiredAt");

                    b.ToTable("AlertsFired");
                });

            modelBuilder.Entity("LogVault.Domain.Entities.AlertRecipient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AlertRuleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AlertRuleId");

                    b.ToTable("AlertRecipients");
                });

            modelBuilder.Entity("LogVault.Domain.Entities.AlertRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FilterExpression")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastFiredAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinimumLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceApplicationFilter")
                        .HasColumnType("TEXT");

                    b.Property<int>("ThrottleMinutes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("AlertRules");
                });

            modelBuilder.Entity("LogVault.Domain.Entities.ApiKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DefaultApplication")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ExpiresAt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("RotatedFromId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("KeyHash")
                        .IsUnique();

                    b.HasIndex("RotatedFromId");

                    b.HasIndex("IsEnabled", "IsRevoked", "ExpiresAt");

                    b.ToTable("ApiKeys");
                });

            modelBuilder.Entity("LogVault.Domain.Entities.LogEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Exception")
                        .HasColumnType("TEXT");

                    b.Property<long>("IngestedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MessageTemplate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PropertiesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RenderedMessage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceApplication")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceEnvironment")
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceHost")
                        .HasColumnType("TEXT");

                    b.Property<string>("SpanId")
                        .HasColumnType("TEXT");

                    b.Property<long>("Timestamp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TraceId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IngestedAt");

                    b.HasIndex("SourceApplication");

                    b.HasIndex("TraceId");

                    b.HasIndex("Timestamp", "Level");

                    b.ToTable("LogEvents");
                });

            modelBuilder.Entity("LogVault.Domain.Entities.AlertFired", b =>
                {
                    b.HasOne("LogVault.Domain.Entities.AlertRule", "AlertRule")
                        .WithMany()
                        .HasForeignKey("AlertRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlertRule");
                });

            modelBuilder.Entity("LogVault.Domain.Entities.AlertRecipient", b =>
                {
                    b.HasOne("LogVault.Domain.Entities.AlertRule", "AlertRule")
                        .WithMany("Recipients")
                        .HasForeignKey("AlertRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlertRule");
                });

            modelBuilder.Entity("LogVault.Domain.Entities.ApiKey", b =>
                {
                    b.HasOne("LogVault.Domain.Entities.ApiKey", "RotatedFrom")
                        .WithMany()
                        .HasForeignKey("RotatedFromId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("RotatedFrom");
                });

            modelBuilder.Entity("LogVault.Domain.Entities.AlertRule", b =>
                {
                    b.Navigation("Recipients");
                });
#pragma warning restore 612, 618
        }
    }
}
